version: '3'
services:
  fritzbox-prometheus-exporter:
    hostname: fritzbox-prometheus-exporter
    build:
      context: .
      dockerfile: Dockerfile
    container_name: fritzbox-prometheus-exporter
    ports:
      - "9042:9042"
    #expose:
    #  - "9042"
    restart: unless-stopped
    environment:
      USERNAME: your_fritzbox_username 
      PASSWORD: your_fritzbox_password
      GATEWAY_URL: http://192.168.0.1:49000
      LISTEN_ADDRESS: 0.0.0.0:9042
